config/routes.rb
Rails.application.routes.draw do

  get 'session/new'
  post 'session/login'
  get 'users/signup'
  get 'welcome/index'
  get 'journey/index'

  resources :users
  resources :session

  root 'welcome#index'

end

app/models/users.rb
class Users < ActiveRecord::Base
  	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include ApplicationHelper
end

app/controllers/journey_controller.rb
class JourneyController < ApplicationController
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  
  def new
    @user = current_user || Users.new
  end

	def login
		@user = Users.find_by_username(params[:username].downcase)
		if @user && @user.authenticate(params[:password])
    	session[:user_id] = @user.id
    	@session = session
    	@fail = false
    	redirect_to(journey_index_path)
  	else
  		print @user.errors.full_messages.last
    	@fail = true
    	redirect_to("/")
  	end
	end

  def logout
    session.clear
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	def new
		@user = Users.new
	end

	def create
 		@user = Users.new(user_params)
    if @user.save
      session[:current_user_id] = @user.id
      redirect_to(journey_index_path)
    else
    	print @user.errors.full_messages.last
      redirect_to :back
    end
	end

	private
  def user_params
    params.require(:users).permit(:username, :first_name, :last_name, :email, :password, :password_confirmation)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_user
    @_current_user ||= session[:current_user_id] &&
                       Users.find_by_id(session[:current_user_id])
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/journey_helper.rb
module JourneyHelper
end

app/helpers/session_helper.rb
module SessionHelper


end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/journey/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <script type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyClJmJ1wK6rcKq6m8dJ06E-dg0ASBF1l0Q">
    </script>
    <script type="text/javascript">
      var geocoder;
      var map;
      function initialize() {
        geocoder = new google.maps.Geocoder();
        var latlng = new google.maps.LatLng(-34.397, 150.644);
        var mapOptions = {
        zoom: 8,
        center: latlng
      }
      map = new google.maps.Map(document.getElementById("map-canvas"), mapOptions);
    }

    function codeAddress() {
      var address = document.getElementById("address").value;
      geocoder.geocode( { 'address': address}, function(results, status) {
        if (status == google.maps.GeocoderStatus.OK) {
          map.setCenter(results[0].geometry.location);
          var marker = new google.maps.Marker({
              map: map,
              position: results[0].geometry.location
          })
          var theDiv = document.getElementById('testing');
          var content = document.createTextNode("Testing");
            theDiv.appendChild(content);;
        } else {
          alert("Geocode was not successful for the following reason: " + status);
        }
      });
    }
    </script>

    <body onload="initialize()">
    <div id="map-canvas" style="width: 320px; height: 480px;"></div>
      <div>
        <input id="address" type="textbox" value="Sydney, NSW">
        <input type="button" value="Encode" onclick="codeAddress()">
      </div>
      <div id="testing"></div>
    </body>
  </head>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Roadtrip</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/session/login.html.erb
<h1> Login </h1>

<% if current_user == nil %>
<p> You need to be signed in to see the possible trips! Sign in below or <%= link_to "Sign Up", new_user_path %> </a> today</p>
<% end %>

<% if @fail == true %>
<p> The username and password do not match, please try again </p>
<% end %>

<%= form_tag session_login_path, {:method => :post} do %>
  <div>
    <label for="user[username]">Username:</label>
    <input type="text" name="user[username]">
  </div>
  <div>
    <label for="user[password]">Password:</label>
    <input type="password" name="user[password]">
  </div>
  <%= submit_tag %>
<% end %>

app/views/session/new.html.erb
  <h4>log in</h4>

  <%= form_tag session_login_path do %>
    <%= text_field_tag    :username,    nil, :placeholder => "Username", :autofocus => true %>
    <%= password_field_tag :password, nil, :placeholder => "Password" %>
    <%= button_tag "Sign In" %>
  <% end %>

app/views/users/new.html.erb
<%= form_for @user, url: {action: "create"} do |f| %>
  <%= f.text_field :username %>
  <%= f.text_field :first_name %>
  <%= f.text_field :last_name %>
  <%= f.email_field :email %>
  <%= password_field(:users, :password) %>
  <%= password_field(:users, :password_confirmation) %>
  
  <%= f.submit "Create" %>
<% end %>

app/views/welcome/index.html.erb
<h1>This is the welcome view </h1>

<h2> Please login below: </h2>

<%= link_to "Login", session_new_path %>

<h2> Or sign up: </h2>
<%= link_to "Sign up", new_user_path %>